# Generated by Django 4.2.10 on 2026-04-03 01:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Short title for the transaction.', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Transaction amount. Must be positive.', max_digits=14, validators=[django.core.validators.MinValueValidator(0.01, message='Amount must be greater than zero.')])),
                ('category', models.CharField(db_index=True, help_text='Free-text category label (e.g. Salary, Rent, Travel).', max_length=100)),
                ('description', models.TextField(blank=True, default='', help_text='Optional notes or context about the transaction.')),
                ('transaction_type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], db_index=True, help_text='Whether this is income or an expense.', max_length=10)),
                ('date', models.DateField(db_index=True, help_text='The date the transaction occurred (YYYY-MM-DD).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financial_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Financial Record',
                'verbose_name_plural': 'Financial Records',
                'db_table': 'financial_records',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['date'], name='financial_r_date_c7ef46_idx'), models.Index(fields=['category'], name='financial_r_categor_2871f2_idx'), models.Index(fields=['transaction_type'], name='financial_r_transac_80c6b3_idx'), models.Index(fields=['created_by', 'date'], name='financial_r_created_5ae785_idx'), models.Index(fields=['transaction_type', 'date'], name='financial_r_transac_d97e06_idx')],
            },
        ),
    ]
