# Generated by Django 4.2.10 on 2026-04-05 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialrecord',
            name='category',
            field=models.CharField(choices=[('Education', 'Education'), ('Entertainment', 'Entertainment'), ('Food & Dining', 'Food & Dining'), ('Groceries', 'Groceries'), ('Health', 'Health'), ('Investments', 'Investments'), ('Rent', 'Rent'), ('Salary', 'Salary'), ('Travel', 'Travel'), ('Utilities', 'Utilities'), ('Other', 'Other')], db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='financialrecord',
            name='title',
            field=models.CharField(help_text='Short title for the transaction.', max_length=50),
        ),
    ]
